ssg-build-job!!:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - git init
    - git status
    - git pull
    - echo $JOB_START
    - hostname -I
    - ls -al
    - echo $JOB_END
  only:
    - dev
  tags:
    - monitoring-cicd