ssg-build-job!:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - git status
    - rm -rf cloud-monitoring
    - git clone --branch dev http://10.99.2.66:19494/KIMSOL/cloud-monitoring.git
    - echo $JOB_START
    - hostname -I
    - ls -al
    - echo $JOB_END
  only:
    - dev
  tags:
    - monitoring-cicd