ssg-build-job!!!!!:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - git remote set-url origin http://10.99.2.66:19494/KIMSOL/cloud-monitoring.git
    - git fetch --all
    - git checkout dev
    - echo $JOB_START
    - hostname -I
    - ls -al
    - echo $JOB_END
  only:
    - dev
  tags:
    - monitoring-cicd