ssg-build-job!:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - git status
    - git checkout dev
    - git pull origin dev
    - echo $JOB_START
    - hostname -I
    - ls -al
    - echo $JOB_END
  only:
    - dev
  tags:
    - monitoring-cicd